"""add unique constraint to application position + company

Revision ID: 4a22563a4a0c
Revises: c40db5eeb35d
Create Date: 2026-08-28 18:35:56.522133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a22563a4a0c'
down_revision: Union[str, Sequence[str], None] = 'c40db5eeb35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_company_position', 'applications', ['company', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_application_company_position', 'applications', type_='unique')
    # ### end Alembic commands ###
