"""create applications table

Revision ID: c40db5eeb35d
Revises: 
Create Date: 2026-08-27 01:46:07.183640

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c40db5eeb35d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'REJECTED', 'INTERVIEW', 'OFFER', name='applicationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')

    application_status = sa.Enum(
        'APPLIED',
        'REJECTED',
        'INTERVIEW',
        'OFFER',
        name='applicationstatus'
    )

    application_status.drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
